### ISSUE TITLE
Merge API markdown files into Readme

### ISSUE THREAD

**Issue by Subhash3** [Subhash3/Neural_Net_Using_NumPy#10]
Docs are currently stored in `docs/markdown/*.md`. I want to merge all those .md files and embed the markdown in the root README under the API section.

**Comment by sawradip** [comment]
Hello Subhash. You have an awesome project here. Implementing NNs from scratch is one of my cherished goals. 

I would like to handle this issue. This is my first time contributing to an open source project. It would be great if you could elaborate me if the task is just to adding the contents on docs folder to the readme file?

**Comment by Subhash3** [comment]
Thanks a lot for checking out this repo @sawradip. 

Yes, I want the `docs/markdown/*.md` files to be merged and written into the README file. But, I want to automate this process.  
  
Here is what I mean:
- The markdown files in `docs/markdown` are generated by  `nicedoc/generate_markdown_api.py`.
- I want to create another script that can merge those `.md` files and write the contents into the README under the API section.
- So, the readme would look something like:
```
..............
..............
# API
(Merged contents of docs/markdown/*.md)
...............
...............
```

**Comment by sawradip** [comment]
I am looking into this @Subhash3

**Comment by Subhash3** [comment]
Checkout the [fix here](https://github.com/Subhash3/Neural_Net_Using_NumPy/pull/11)
