### ISSUE TITLE
Convert all camel-cased variables & functions to snake-case.

### ISSUE THREAD

**Issue by Subhash3** [Subhash3/Neural_Net_Using_NumPy#3]
The codebase uses both camel casing and snake casing. I want all the camel cases to be converted to snake case.

For eg: `setLearningRate` needs to changed to `set_learning_rate`.

Work on file by file:
```md
    - [ ] convert all camel-cased vars to snake-case.
        - [ ] NeuralNetwork.py
        - [ ] Layer.py
        - [ ] Dataset.py
        - [ ] ActivationFunction.py
        - [ ] Utils.py
        - [ ] LossFunctions.py
```

There are many ways to achieve this:
- Using regex.
- Using vscode keyboard-shortcut `editor.action.transformToSnakecase`.

NOTE: Do not modify any file other than the ones listed above.
If possible, implement a conversion algorithm that accepts a python file and converts every single instance of camel-case to snake-case and writes the modified contents into a new file.

Its prototype may look something like:
```python
def convert_camel_to_snake(pyfile:str) -> None:
    # Parse the file and write the new contents to pyfile.out
```

**Comment by buddheshwarnathkeshari** [comment]
#5 converted camelcase to snake_case
