### ISSUE TITLE
Runtime warning in activation functions.

### ISSUE THREAD

**Issue by Subhash3** [Subhash3/Neural_Net_Using_NumPy#7]
Decimal overflows in activation functions.

E.g: In sigmoid function
```python
RuntimeWarning: overflow encountered in exp
        return 1/(1 + np.exp(-x))
```

**Comment by syedmalimustafa** [comment]
Have a look into this: https://stackoverflow.com/questions/40726490/overflow-error-in-pythons-numpy-exp-function

**Comment by Subhash3** [comment]
Thanks for the resource @alimustafashah. That helped.
